/*
 * Copyright (c) 2026 Standard Applied Intelligence Labs
 * SPDX-License-Identifier: MIT
 */

package ai.singlr.sail.engine;

import ai.singlr.sail.store.FdeSshKeyStore;
import java.util.List;
import java.util.regex.Pattern;

/**
 * Renders the {@code sail} user's {@code authorized_keys} from the registry. Each registered key
 * becomes a forced-command line that pins it to the gateway for exactly one FDE:
 *
 * <pre>{@code
 * command="/usr/local/bin/sail _gateway --fde uday",restrict ssh-ed25519 AAAA... uday@laptop
 * }</pre>
 *
 * <p>The FDE handle is interpolated inside the {@code command="..."} quotes, so a handle containing
 * a quote or whitespace could break out and inject options. The renderer is therefore fail-closed:
 * it rejects any handle that is not a conservative {@code [A-Za-z0-9._-]+}, refusing to emit the
 * whole file rather than write a line that could widen what a key may run.
 */
public final class AuthorizedKeysRenderer {

  private static final Pattern SAFE_HANDLE = Pattern.compile("[A-Za-z0-9._-]+");
  private static final String HEADER =
      "# Managed by sail — regenerated by 'sail host keys sync'. Do not edit by hand.";

  private AuthorizedKeysRenderer() {}

  public static String render(List<FdeSshKeyStore.SshKeyInfo> keys, String sailBinary) {
    var out = new StringBuilder(HEADER).append('\n');
    for (var key : keys) {
      if (!SAFE_HANDLE.matcher(key.fdeHandle()).matches()) {
        throw new IllegalArgumentException(
            "Refusing to render authorized_keys: unsafe FDE handle '" + key.fdeHandle() + "'.");
      }
      out.append("command=\"")
          .append(sailBinary)
          .append(" _gateway --fde ")
          .append(key.fdeHandle())
          .append("\",restrict ")
          .append(key.publicKey())
          .append('\n');
    }
    return out.toString();
  }
}
